/* v8 ignore file -- @preserve */

import autoLoad from "@fastify/autoload";
import openapi from "@fastify/swagger";
import openapiUi from "@fastify/swagger-ui";
import Fastify from "fastify";
import { join } from "node:path";
import { Config } from "./shared/config.js";

const fastify = Fastify({
  logger:
    Config.env == "development"
      ? {
          transport: {
            target: "pino-pretty",
            options: {
              translateTime: "SYS:standard",
              ignore: "pid,hostname",
              hideObject: true,
              messageFormat:
                "{if reqId}[{reqId}]{end} {if req.url}[{req.method}][{req.url}]{end} {if responseTime}[{res.statusCode}][{responseTime}ms]{end} {msg}",
            },
          },
        }
      : false,
});

const setup = async () => {
  await fastify.register(openapi, {
    openapi: {
      openapi: "3.0.0",
      info: {
        title: "API",
        description: "The API documentation generated by Fastify Swagger",
        version: "0.0.0",
      },
      servers: [
        {
          url: "http://localhost:3000",
          description: "Development server",
        },
      ],
    },
  });

  await fastify.register(openapiUi, {
    routePrefix: "/api",
    uiConfig: {
      persistAuthorization: true,
      tagsSorter: "alpha",
      operationsSorter: "alpha",
      syntaxHighlight: {
        theme: "nord",
      },
    },
  });

  await fastify.register(autoLoad, {
    dir: join(import.meta.dirname, "routes"),
  });
};

const main = async () => {
  try {
    await setup();
    await fastify.listen({ port: 5000 });
  } catch (error) {
    fastify.log.error(error);
    process.exit(1);
  }
};

main();
