import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next.js Boilderplate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
